- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        children:
          molecule:
            hosts: {}

  tasks:
    - name: Create a container
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        privileged: "{{ item.privileged | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        capabilities: "{{ item.capabilities | default(omit) }}"
        systemd: "{{ item.systemd | default(omit) }}"
        state: started
        command: "{{ item.command | default('sleep 1d') }}"
        # bash -c "while true; do sleep 10000; done"
        log_driver: json-file
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ result.results }}"
        verbosity: 2

    - name: Fail if container is not running
      when: >
        item.container.State.ExitCode != 0 or
        not item.container.State.Running
      ansible.builtin.fail:
        msg: "Container '{{ item.container.Name }}' is not running"
      loop: "{{ result.results }}"
      loop_control:
        label: "{{ item.container.Name }}"

    - name: Add container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                hosts:
                  "{{ item.name }}":
                    ansible_connection: containers.podman.podman
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Force inventory refresh
      ansible.builtin.meta: refresh_inventory

    - name: Fail if molecule group is missing
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}
        quiet: true
      run_once: true # noqa: run-once[task]

# we want to avoid errors like "Failed to create temporary directory"
- name: Install Python
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Install python on debian based distros
      ansible.builtin.raw: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install --yes python3
      args:
        executable: /bin/bash
      register: result
      changed_when: |
        "python3 is already the newest version" not in result.stdout
      when: |
        "test_family_debian" in group_names

    - name: Install python on fedora based distros
      ansible.builtin.raw: |
        dnf install --assumeyes python3
      args:
        executable: /bin/bash
      register: result
      changed_when: |
        "Nothing to do" not in result.stdout
      when: |
        "test_family_fedora" in group_names

    - name: Install python on Alpine Linux based distros
      ansible.builtin.raw: |
        apk add --no-cache python3
      args:
        executable: /bin/sh
      register: result
      changed_when: |
        "Installing" in result.stdout
      when: |
        "test_family_alpine" in group_names

    - name: Install python on ArchLinux based distros
      ansible.builtin.raw: |
        pacman --sync --refresh --noconfirm python
      args:
        executable: /bin/bash
      register: result
      changed_when: |
        "installing" in result.stdout
      when: |
        "test_family_archlinux" in group_names
